FROM prashanthmadi/appservice-nginx-php-fpm:latest

# mariadb
ENV MARIADB_DATA_DIR="/var/lib/mysql"
ENV MARIADB_LOG_DIR="/var/log/mysql"
ENV MARIADB_DATA_DIR_TEMP="/tmp/mariadb"

# magento ce
ENV MAGENTO_VERSION "2.1.5"
ENV MAGENTO_PACKAGE "Magento-CE-$MAGENTO_VERSION.tar.gz"
ENV MAGENTO_SOURCE "/usr/src/magento"
ENV MAGENTO_HOME "/var/www/html/magento"
ENV PATH "$MAGENTO_HOME/bin":$PATH

RUN apt-get update \
    # ------------	
	# 1. Install Mariadb
	# ------------
    && DEBIAN_FRONTEND=noninteractive apt-get install mariadb-server -y -V --no-install-recommends \
    # ------------	
	# 2. magento ce
	# ------------
	&& mkdir -p $MAGENTO_SOURCE \
    && mkdir -p $MAGENTO_HOME \
	&& cd $DOCKER_BUILD_HOME \
	&& tar -xf $MAGENTO_PACKAGE -C $MAGENTO_SOURCE \
	&& rm $DOCKER_BUILD_HOME/$MAGENTO_PACKAGE \
    # -------
	# 3. cron
	# -------
	&& apt-get install cron -y -V --no-install-recommends \
	&& rm -r /var/lib/apt/lists/* 


COPY nginx.conf /etc/nginx/nginx.conf